// <auto-generated />
using System;
using AspKnP231.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspKnP231.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260329212234_AddShopTables")]
    partial class AddShopTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspKnP231.Data.Entities.ShopProduct", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ImageUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<Guid>("ShopSectionId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Slug")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Stock")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("ShopSectionId");

                b.ToTable("ShopProducts");
            });

            modelBuilder.Entity("AspKnP231.Data.Entities.ShopSection", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ImageUrl")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("ParentId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Slug")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("ShopSections");
            });

            modelBuilder.Entity("AspKnP231.Data.Entities.UserAccess", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AvatarFilename")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Dk")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Login")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Salt")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("UserRoleId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("Login")
                    .IsUnique();

                b.HasIndex("UserId");

                b.HasIndex("UserRoleId");

                b.ToTable("UserAccesses");

                b.HasData(
                    new
                    {
                        Id = new Guid("f749f994-af12-4ea1-8bef-829ef751fc4a"),
                        CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Dk = "4E455301C8628F110EADAB21A780FF766CFE0B95",
                        Login = "DefaultAdministrator",
                        Salt = "380B5CB5-1578-49A2-BCAF-4A1CA8AA9BC2",
                        UserId = new Guid("ae3a3665-8f44-4a2c-95a4-8bbccba7c80d"),
                        UserRoleId = new Guid("250fa2d3-0818-42d6-a1ed-112f115407d6")
                    });
            });

            modelBuilder.Entity("AspKnP231.Data.Entities.UserData", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("Birthdate")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeletedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("UsersData");

                b.HasData(
                    new
                    {
                        Id = new Guid("ae3a3665-8f44-4a2c-95a4-8bbccba7c80d"),
                        Birthdate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Email = "admin@change.me",
                        Name = "Default Administrator"
                    });
            });

            modelBuilder.Entity("AspKnP231.Data.Entities.UserRole", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("CreateLevel")
                    .HasColumnType("int");

                b.Property<int>("DeleteLevel")
                    .HasColumnType("int");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("ReadLevel")
                    .HasColumnType("int");

                b.Property<int>("UpdateLevel")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("UserRoles");

                b.HasData(
                    new
                    {
                        Id = new Guid("28578d03-1e83-4607-9fb0-631fed207dcf"),
                        CreateLevel = 0,
                        DeleteLevel = 0,
                        Description = "Користувачі, що самі зареєструвались на сайті. Мінімальні права доступу",
                        Name = "Self Registered",
                        ReadLevel = 0,
                        UpdateLevel = 0
                    },
                    new
                    {
                        Id = new Guid("250fa2d3-0818-42d6-a1ed-112f115407d6"),
                        CreateLevel = -1,
                        DeleteLevel = -1,
                        Description = "Користувач з максимальним доступом, через якого вводяться інші ролі та доступи",
                        Name = "Root Administrator",
                        ReadLevel = -1,
                        UpdateLevel = -1
                    });
            });

            modelBuilder.Entity("AspKnP231.Data.Entities.ShopProduct", b =>
            {
                b.HasOne("AspKnP231.Data.Entities.ShopSection", "Section")
                    .WithMany("Products")
                    .HasForeignKey("ShopSectionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Section");
            });

            modelBuilder.Entity("AspKnP231.Data.Entities.UserAccess", b =>
            {
                b.HasOne("AspKnP231.Data.Entities.UserData", "UserData")
                    .WithMany("UserAccesses")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("AspKnP231.Data.Entities.UserRole", "UserRole")
                    .WithMany()
                    .HasForeignKey("UserRoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("UserData");

                b.Navigation("UserRole");
            });

            modelBuilder.Entity("AspKnP231.Data.Entities.ShopSection", b =>
            {
                b.Navigation("Products");
            });

            modelBuilder.Entity("AspKnP231.Data.Entities.UserData", b =>
            {
                b.Navigation("UserAccesses");
            });
#pragma warning restore 612, 618
        }
    }
}